@startuml
skinparam componentStyle rectangle
title AndroidModApp - Mapa de módulos (multimódulo)

component "app" as APP

package "core" {
  component "common"
  component "designsystem"
  component "resources"
  component "ui"
}

package "domain" {
  component "models"
  component "mappers"
  component "managers"
  component "services"
  package "usescases" {
    component "analytics"
    component "opendb"
    component "settings"
  }
}

package "data" {
  component "analytics"
  component "authentication"
  component "couchbase"
  component "datastore"
  component "files"
  component "firestore"
  component "realtime"
  component "repositories"
  component "retrofit"
  component "room"
}

package "feature" {
  component "main"
  component "mvisample"
  component "mvvmsample"
  component "splash"
}

APP --> core
APP --> domain
APP --> feature

feature ..> domain : usa UseCases / modelos
feature ..> core

domain ..> data : contratos / puertos
domain ..> core : utilidades

data ..> domain : implementa repositorios
data ..> core

core -- core : reutilización interna
@enduml
