@startuml
title Paquetes principales - core

package "core" {
  package "common" {
    [Utils]
    [Extensions]
  }
  package "designsystem" {
    [Theme]
    [Components]
  }
  package "resources" {
    [Strings]
    [Colors]
  }
  package "ui" {
    [BaseActivity]
    [BaseFragment]
  }
}

common --> designsystem
ui --> designsystem
ui --> common
@enduml
