@startuml
title Paquetes principales - domain

package "domain" {
  package "models" {
    class Entity
    class DTO
  }
  package "mappers" {
    [EntityMapper]
  }
  package "managers" {
    [AuthManager]
  }
  package "services" {
    [BusinessService]
  }
  package "usescases" {
    [GetItemsUseCase]
    [SaveItemUseCase]
  }
}

usescases --> models
usescases --> mappers
services --> managers
@enduml
