@startuml
title Paquetes - ejemplo de feature (splash / main / samples)

package "feature.main" {
  package "ui" {
    [MainActivity]
    [MainFragment]
  }
  package "di" {
    [MainModule]
  }
  package "presentation" {
    [MainViewModel]
  }
}

MainViewModel --> MainModule
MainActivity --> MainViewModel
MainFragment --> MainViewModel
@enduml
