package es.sebas1705.ui.theme

import androidx.compose.ui.graphics.Color

// Light low contrast color palette
val primaryLightLowContrast = Color(0xFF584275)
val onPrimaryLightLowContrast = Color(0xFFFFFFFF)
val primaryContainerLightLowContrast = Color(0xFFEEDCFF)
val onPrimaryContainerLightLowContrast = Color(0xFF260E44)
val secondaryLightLowContrast = Color(0xFF5F5790)
val onSecondaryLightLowContrast = Color(0xFFFFFFFF)
val secondaryContainerLightLowContrast = Color(0xFFE5DEFF)
val onSecondaryContainerLightLowContrast = Color(0xFF1B1149)
val tertiaryLightLowContrast = Color(0xFF8B4F26)
val onTertiaryLightLowContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightLowContrast = Color(0xFFFFDBC8)
val onTertiaryContainerLightLowContrast = Color(0xFF321300)
val errorLightLowContrast = Color(0xFF904A43)
val onErrorLightLowContrast = Color(0xFFFFFFFF)
val errorContainerLightLowContrast = Color(0xFFFFDAD6)
val onErrorContainerLightLowContrast = Color(0xFF3B0907)
val backgroundLightLowContrast = Color(0xFFFFF7FF)
val onBackgroundLightLowContrast = Color(0xFF1D1A20)
val surfaceLightLowContrast = Color(0xFFF5FAFB)
val onSurfaceLightLowContrast = Color(0xFF161D1D)
val surfaceVariantLightLowContrast = Color(0xFFDFE4D7)
val onSurfaceVariantLightLowContrast = Color(0xFF43483F)
val outlineLightLowContrast = Color(0xFF73796E)
val outlineVariantLightLowContrast = Color(0xFFC3C8BC)
val scrimLightLowContrast = Color(0xFF000000)
val inverseSurfaceLightLowContrast = Color(0xFF2B3232)
val inverseOnSurfaceLightLowContrast = Color(0xFFECF2F2)
val inversePrimaryLightLowContrast = Color(0xFFD7BAFB)
val surfaceDimLightLowContrast = Color(0xFFD5DBDC)
val surfaceBrightLightLowContrast = Color(0xFFF5FAFB)
val surfaceContainerLowestLightLowContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightLowContrast = Color(0xFFEFF5F5)
val surfaceContainerLightLowContrast = Color(0xFFE9EFEF)
val surfaceContainerHighLightLowContrast = Color(0xFFE3E9EA)
val surfaceContainerHighestLightLowContrast = Color(0xFFDEE4E4)
//--------------------------------------------------------------------

// Light medium contrast color palette
val primaryLightMediumContrast = Color(0xFF4F376E)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF8369A4)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF433B73)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF766DA8)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF6A340C)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFA66539)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF6E302A)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFAA6057)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF7FF)
val onBackgroundLightMediumContrast = Color(0xFF1D1A20)
val surfaceLightMediumContrast = Color(0xFFF5FAFB)
val onSurfaceLightMediumContrast = Color(0xFF161D1D)
val surfaceVariantLightMediumContrast = Color(0xFFDFE4D7)
val onSurfaceVariantLightMediumContrast = Color(0xFF3F453B)
val outlineLightMediumContrast = Color(0xFF5B6156)
val outlineVariantLightMediumContrast = Color(0xFF777D71)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3232)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F2)
val inversePrimaryLightMediumContrast = Color(0xFFD7BAFB)
val surfaceDimLightMediumContrast = Color(0xFFD5DBDC)
val surfaceBrightLightMediumContrast = Color(0xFFF5FAFB)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F5)
val surfaceContainerLightMediumContrast = Color(0xFFE9EFEF)
val surfaceContainerHighLightMediumContrast = Color(0xFFE3E9EA)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDEE4E4)
//--------------------------------------------------------------------

// Light high contrast color palette
val primaryLightHighContrast = Color(0xFF2D154B)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF4F376E)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF221950)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF433B73)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF3C1800)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF6A340C)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF44100C)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF6E302A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF7FF)
val onBackgroundLightHighContrast = Color(0xFF1D1A20)
val surfaceLightHighContrast = Color(0xFFF5FAFB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDFE4D7)
val onSurfaceVariantLightHighContrast = Color(0xFF20251D)
val outlineLightHighContrast = Color(0xFF3F453B)
val outlineVariantLightHighContrast = Color(0xFF3F453B)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B3232)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFF5E7FF)
val surfaceDimLightHighContrast = Color(0xFFD5DBDC)
val surfaceBrightLightHighContrast = Color(0xFFF5FAFB)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEFF5F5)
val surfaceContainerLightHighContrast = Color(0xFFE9EFEF)
val surfaceContainerHighLightHighContrast = Color(0xFFE3E9EA)
val surfaceContainerHighestLightHighContrast = Color(0xFFDEE4E4)
//--------------------------------------------------------------------

// Dark low contrast color palette
val primaryDarkLowContrast = Color(0xFFD7BAFB)
val onPrimaryDarkLowContrast = Color(0xFF3C255A)
val primaryContainerDarkLowContrast = Color(0xFF533B72)
val onPrimaryContainerDarkLowContrast = Color(0xFFEEDCFF)
val secondaryDarkLowContrast = Color(0xFFC9BFFF)
val onSecondaryDarkLowContrast = Color(0xFF31285F)
val secondaryContainerDarkLowContrast = Color(0xFF473F77)
val onSecondaryContainerDarkLowContrast = Color(0xFFE5DEFF)
val tertiaryDarkLowContrast = Color(0xFFFFB68A)
val onTertiaryDarkLowContrast = Color(0xFF522300)
val tertiaryContainerDarkLowContrast = Color(0xFF6F3810)
val onTertiaryContainerDarkLowContrast = Color(0xFFFFDBC8)
val errorDarkLowContrast = Color(0xFFFFB4AB)
val onErrorDarkLowContrast = Color(0xFF561E19)
val errorContainerDarkLowContrast = Color(0xFF73332D)
val onErrorContainerDarkLowContrast = Color(0xFFFFDAD6)
val backgroundDarkLowContrast = Color(0xFF151218)
val onBackgroundDarkLowContrast = Color(0xFFE7E0E8)
val surfaceDarkLowContrast = Color(0xFF0E1415)
val onSurfaceDarkLowContrast = Color(0xFFDEE4E4)
val surfaceVariantDarkLowContrast = Color(0xFF43483F)
val onSurfaceVariantDarkLowContrast = Color(0xFFC3C8BC)
val outlineDarkLowContrast = Color(0xFF8D9387)
val outlineVariantDarkLowContrast = Color(0xFF43483F)
val scrimDarkLowContrast = Color(0xFF000000)
val inverseSurfaceDarkLowContrast = Color(0xFFDEE4E4)
val inverseOnSurfaceDarkLowContrast = Color(0xFF2B3232)
val inversePrimaryDarkLowContrast = Color(0xFF6C538C)
val surfaceDimDarkLowContrast = Color(0xFF0E1415)
val surfaceBrightDarkLowContrast = Color(0xFF343A3B)
val surfaceContainerLowestDarkLowContrast = Color(0xFF090F10)
val surfaceContainerLowDarkLowContrast = Color(0xFF161D1D)
val surfaceContainerDarkLowContrast = Color(0xFF1A2121)
val surfaceContainerHighDarkLowContrast = Color(0xFF252B2C)
val surfaceContainerHighestDarkLowContrast = Color(0xFF303637)
//--------------------------------------------------------------------

// Dark medium contrast color palette
val primaryDarkMediumContrast = Color(0xFFDCBFFF)
val onPrimaryDarkMediumContrast = Color(0xFF20073E)
val primaryContainerDarkMediumContrast = Color(0xFFA085C2)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFCDC3FF)
val onSecondaryDarkMediumContrast = Color(0xFF160B44)
val secondaryContainerDarkMediumContrast = Color(0xFF9289C7)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFBC94)
val onTertiaryDarkMediumContrast = Color(0xFF2A0F00)
val tertiaryContainerDarkMediumContrast = Color(0xFFC78052)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF330404)
val errorContainerDarkMediumContrast = Color(0xFFCC7B72)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF151218)
val onBackgroundDarkMediumContrast = Color(0xFFE7E0E8)
val surfaceDarkMediumContrast = Color(0xFF0E1415)
val onSurfaceDarkMediumContrast = Color(0xFFF6FCFC)
val surfaceVariantDarkMediumContrast = Color(0xFF43483F)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC7CDC0)
val outlineDarkMediumContrast = Color(0xFF9FA599)
val outlineVariantDarkMediumContrast = Color(0xFF7F857A)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE4E4)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2C)
val inversePrimaryDarkMediumContrast = Color(0xFF543D74)
val surfaceDimDarkMediumContrast = Color(0xFF0E1415)
val surfaceBrightDarkMediumContrast = Color(0xFF343A3B)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF090F10)
val surfaceContainerLowDarkMediumContrast = Color(0xFF161D1D)
val surfaceContainerDarkMediumContrast = Color(0xFF1A2121)
val surfaceContainerHighDarkMediumContrast = Color(0xFF252B2C)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF303637)
//--------------------------------------------------------------------

// Dark high contrast color palette
val primaryDarkHighContrast = Color(0xFFFFF9FC)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFDCBFFF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFEF9FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFCDC3FF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFFAF8)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFBC94)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF151218)
val onBackgroundDarkHighContrast = Color(0xFFE7E0E8)
val surfaceDarkHighContrast = Color(0xFF0E1415)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF43483F)
val onSurfaceVariantDarkHighContrast = Color(0xFFF7FDEF)
val outlineDarkHighContrast = Color(0xFFC7CDC0)
val outlineVariantDarkHighContrast = Color(0xFFC7CDC0)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE4E4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF351E53)
val surfaceDimDarkHighContrast = Color(0xFF0E1415)
val surfaceBrightDarkHighContrast = Color(0xFF343A3B)
val surfaceContainerLowestDarkHighContrast = Color(0xFF090F10)
val surfaceContainerLowDarkHighContrast = Color(0xFF161D1D)
val surfaceContainerDarkHighContrast = Color(0xFF1A2121)
val surfaceContainerHighDarkHighContrast = Color(0xFF252B2C)
val surfaceContainerHighestDarkHighContrast = Color(0xFF303637)
//--------------------------------------------------------------------





